from .hybrid_b3_tianchi2_label import config as hybrid_b3_tianchi2_label
from .segformer_b3_tianchi2_label import config as segformer_b3_tianchi2_label
from .hybrid_b4_tianchi2_label import config as hybrid_b4_tianchi2_label
from .segformer_b4_tianchi2_label import config as segformer_b4_tianchi2_label


from .deeplabv3plus_tianchi2_label_no_overlap import config as deeplabv3plus_tianchi2_label_no_overlap
from .segformer_b3_tianchi2_label_no_overlap import config as segformer_b3_tianchi2_label_no_overlap
from .segformer_b4_tianchi2_label_no_overlap import config as segformer_b4_tianchi2_label_no_overlap
from .hybrid_b4_tianchi2_label_no_overlap import config as hybrid_b4_tianchi2_label_no_overlap
from .hybrid_b3_tianchi2_label_no_overlap import config as hybrid_b3_tianchi2_label_no_overlap
from .unet_tianchi2_label_no_overlap import config as unet_tianchi2_label_no_overlap