from .deeplabv3plus_tianchi_2 import config as deeplabv3plus_tianchi_2

from .segformer_b4_tianchi_2 import config as segformer_b4_tianchi_2
from .segformer_b5_tianchi_2 import config as segformer_b5_tianchi_2
from .segformer_b3_tianchi_2 import config as segformer_b3_tianchi_2

from .hybrid_b4_tianchi_2 import config as hybrid_b4_tianchi_2
from .hybrid_b5_tianchi_2 import config as hybrid_b5_tianchi_2
from .hybrid_b3_tianchi_2 import config as hybrid_b3_tianchi_2


from .deeplabv3plus_tianchi_2_label_random_no_overlap import config as deeplabv3plus_tianchi_2_label_random_no_overlap
from .segformer_b4_tianchi_2_label_random_no_overlap import config as segformer_b4_tianchi_2_label_random_no_overlap
from .hybrid_b4_tianchi_2_label_random_no_overlap import config as hybrid_b4_tianchi_2_label_random_no_overlap